/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("net.wesjd.java-conventions")
}

dependencies {
    compileOnly(libs.org.spigotmc.spigot.x6)
    compileOnly(libs.net.wesjd.anvilgui.v1.v14.v4.r1)
    providedCompile(project(":anvilgui-abstraction"))
}

description = "anvilgui-1_14_R1-spigot"
