rootProject.name = "anvilgui-parent"

include(":api")

// Abstract Modules
include(":anvilgui-nms:anvilgui-abstraction")

// Spigot Modules
include(":anvilgui-nms:anvilgui-nms-spigot:anvilgui-1_7_R4-spigot")
include(":anvilgui-nms:anvilgui-nms-spigot:anvilgui-1_8_R1-spigot")
include(":anvilgui-nms:anvilgui-nms-spigot:anvilgui-1_8_R2-spigot")
include(":anvilgui-nms:anvilgui-nms-spigot:anvilgui-1_8_R3-spigot")
include(":anvilgui-nms:anvilgui-nms-spigot:anvilgui-1_9_R1-spigot")
include(":anvilgui-nms:anvilgui-nms-spigot:anvilgui-1_9_R2-spigot")
include(":anvilgui-nms:anvilgui-nms-spigot:anvilgui-1_10_R1-spigot")
include(":anvilgui-nms:anvilgui-nms-spigot:anvilgui-1_11_R1-spigot")
include(":anvilgui-nms:anvilgui-nms-spigot:anvilgui-1_12_R1-spigot")
include(":anvilgui-nms:anvilgui-nms-spigot:anvilgui-1_13_R1-spigot")
include(":anvilgui-nms:anvilgui-nms-spigot:anvilgui-1_13_R2-spigot")
include(":anvilgui-nms:anvilgui-nms-spigot:anvilgui-1_14_R1-spigot")
include(":anvilgui-nms:anvilgui-nms-spigot:anvilgui-1_14_4_R1-spigot")
include(":anvilgui-nms:anvilgui-nms-spigot:anvilgui-1_15_R1-spigot")
include(":anvilgui-nms:anvilgui-nms-spigot:anvilgui-1_16_R1-spigot")
include(":anvilgui-nms:anvilgui-nms-spigot:anvilgui-1_16_R2-spigot")
include(":anvilgui-nms:anvilgui-nms-spigot:anvilgui-1_16_R3-spigot")
include(":anvilgui-nms:anvilgui-nms-spigot:anvilgui-1_17_R1-spigot")
include(":anvilgui-nms:anvilgui-nms-spigot:anvilgui-1_17_1_R1-spigot")
include(":anvilgui-nms:anvilgui-nms-spigot:anvilgui-1_18_R1-spigot")
include(":anvilgui-nms:anvilgui-nms-spigot:anvilgui-1_18_R2-spigot")
include(":anvilgui-nms:anvilgui-nms-spigot:anvilgui-1_19_R1-spigot")
include(":anvilgui-nms:anvilgui-nms-spigot:anvilgui-1_19_R2-spigot")
include(":anvilgui-nms:anvilgui-nms-spigot:anvilgui-1_19_R3-spigot")
include(":anvilgui-nms:anvilgui-nms-spigot:anvilgui-1_19_1_R1-spigot")
include(":anvilgui-nms:anvilgui-nms-spigot:anvilgui-1_20_R1-spigot")
include(":anvilgui-nms:anvilgui-nms-spigot:anvilgui-1_20_R2-spigot")
include(":anvilgui-nms:anvilgui-nms-spigot:anvilgui-1_20_R3-spigot")
include(":anvilgui-nms:anvilgui-nms-spigot:anvilgui-1_20_R4-spigot")
include(":anvilgui-nms:anvilgui-nms-spigot:anvilgui-1_21_R1-spigot")
include(":anvilgui-nms:anvilgui-nms-spigot:anvilgui-1_21_R2-spigot")
include(":anvilgui-nms:anvilgui-nms-spigot:anvilgui-1_21_R3-spigot")

// Paper Modules
include(":anvilgui-nms:anvilgui-nms-paper:anvilgui-1_7_R4-paper")
include(":anvilgui-nms:anvilgui-nms-paper:anvilgui-1_8_R1-paper")
include(":anvilgui-nms:anvilgui-nms-paper:anvilgui-1_8_R2-paper")
include(":anvilgui-nms:anvilgui-nms-paper:anvilgui-1_8_R3-paper")
include(":anvilgui-nms:anvilgui-nms-paper:anvilgui-1_9_R1-paper")
include(":anvilgui-nms:anvilgui-nms-paper:anvilgui-1_9_R2-paper")
include(":anvilgui-nms:anvilgui-nms-paper:anvilgui-1_10_R1-paper")
include(":anvilgui-nms:anvilgui-nms-paper:anvilgui-1_11_R1-paper")
include(":anvilgui-nms:anvilgui-nms-paper:anvilgui-1_12_R1-paper")
include(":anvilgui-nms:anvilgui-nms-paper:anvilgui-1_13_R1-paper")
include(":anvilgui-nms:anvilgui-nms-paper:anvilgui-1_13_R2-paper")
include(":anvilgui-nms:anvilgui-nms-paper:anvilgui-1_14_R1-paper")
include(":anvilgui-nms:anvilgui-nms-paper:anvilgui-1_14_4_R1-paper")
include(":anvilgui-nms:anvilgui-nms-paper:anvilgui-1_15_R1-paper")
include(":anvilgui-nms:anvilgui-nms-paper:anvilgui-1_16_R1-paper")
include(":anvilgui-nms:anvilgui-nms-paper:anvilgui-1_16_R2-paper")
include(":anvilgui-nms:anvilgui-nms-paper:anvilgui-1_16_R3-paper")
include(":anvilgui-nms:anvilgui-nms-paper:anvilgui-1_17_R1-paper")
include(":anvilgui-nms:anvilgui-nms-paper:anvilgui-1_17_1_R1-paper")
include(":anvilgui-nms:anvilgui-nms-paper:anvilgui-1_18_R1-paper")
include(":anvilgui-nms:anvilgui-nms-paper:anvilgui-1_18_R2-paper")
include(":anvilgui-nms:anvilgui-nms-paper:anvilgui-1_19_R1-paper")
include(":anvilgui-nms:anvilgui-nms-paper:anvilgui-1_19_R2-paper")
include(":anvilgui-nms:anvilgui-nms-paper:anvilgui-1_19_R3-paper")
include(":anvilgui-nms:anvilgui-nms-paper:anvilgui-1_19_1_R1-paper")
include(":anvilgui-nms:anvilgui-nms-paper:anvilgui-1_20_R1-paper")
include(":anvilgui-nms:anvilgui-nms-paper:anvilgui-1_20_R2-paper")
include(":anvilgui-nms:anvilgui-nms-paper:anvilgui-1_20_R3-paper")
include(":anvilgui-nms:anvilgui-nms-paper:anvilgui-1_20_R4-paper")
include(":anvilgui-nms:anvilgui-nms-paper:anvilgui-1_21_R1-paper")
include(":anvilgui-nms:anvilgui-nms-paper:anvilgui-1_21_R2-paper")
include(":anvilgui-nms:anvilgui-nms-paper:anvilgui-1_21_R3-paper")
