/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("net.wesjd.java-conventions")
}

dependencies {
    compileOnly(libs.org.spigotmc.spigot.x22)
    compileOnly(libs.net.wesjd.anvilgui.v1.v19.v1.r1)
    providedCompile(project(":anvilgui-abstraction"))
}

description = "anvilgui-1_19_R1-paper"
